output = """
[
{"item_id":"1","item_name":"Espresso","item_basics":"1 | Espresso | Hot Drinks | $2.75 | $0.65 | 76.4%","sales_metrics":"Momentum 0.05 stable; 831 sales/59d ≈14/d; peak May mornings; avg units/order 1.0","elasticity_indicators":"E 0.76 (med-inelastic)","competitive_position":"Comp avg $3.00; Δ −8.3%; value tier","cost_dynamics":"Bean cost flat; margin steady; no seasonality","price_change_history":"No recent changes","customer_segments":"Commuters & regulars; low price focus","optimization_signals":"Room to +5-8% w/low volume risk"},

{"item_id":"2","item_name":"Double Espresso","item_basics":"2 | Double Espresso | Hot Drinks | $3.50 | $1.10 | 68.6%","sales_metrics":"Momentum 0.08 stable; 797/58d ≈14/d; peak May; avg 1.0/order","elasticity_indicators":"E 0.97 (med-inelastic)","competitive_position":"No direct comps; position parity","cost_dynamics":"Cost steady; margin unchanged","price_change_history":"No recent changes","customer_segments":"Caffeine seekers; med sensitivity","optimization_signals":"Monitor—no urgent action"},

{"item_id":"3","item_name":"Americano","item_basics":"3 | Americano | Hot Drinks | $3.25 | $0.70 | 78.5%","sales_metrics":"Momentum 0.04; 815/58d ≈14/d; peak May; 1.0/order","elasticity_indicators":"E 0.55 (low)","competitive_position":"Comp $3.25; Δ 0.0%; parity","cost_dynamics":"Stable inputs; strong margin","price_change_history":"No changes","customer_segments":"Regular coffee drinkers; low sensitivity","optimization_signals":"Could +3-5% to move above parity"},

{"item_id":"4","item_name":"Cappuccino","item_basics":"4 | Cappuccino | Hot Drinks | $4.50 | $1.25 | 72.2%","sales_metrics":"Momentum 0.02; 757/58d ≈13/d; peak Sep; 1.0/order","elasticity_indicators":"E 0.75 (med-inelastic)","competitive_position":"Comp $4.20; Δ +7.1%; premium","cost_dynamics":"Milk cost up seasonally Q4 (+3%); margin holding","price_change_history":"No recent moves","customer_segments":"Milk-based lovers; med sensitivity","optimization_signals":"Hold—competitors rising, track cost"},

{"item_id":"5","item_name":"Latte","item_basics":"5 | Latte | Hot Drinks | $4.75 | $1.35 | 71.6%","sales_metrics":"Momentum 0.09; 872/58d ≈15/d; peak May; 1.1/order","elasticity_indicators":"E 3.63 (high elastic)","competitive_position":"Comp $4.25; Δ +11.8%; premium","cost_dynamics":"Cost flat; margin solid","price_change_history":"Last +$0.25 90d ago, −6% volume","customer_segments":"Students & commuters; high sensitivity","optimization_signals":"Consider promo/packaging to defend volume"},

{"item_id":"6","item_name":"Flat White","item_basics":"6 | Flat White | Hot Drinks | $4.50 | $1.30 | 71.1%","sales_metrics":"Momentum 0.03; 809/58d; peak May; 1.0/order","elasticity_indicators":"E 3.92 (high)","competitive_position":"No comps; premium niche","cost_dynamics":"Cost +2% dairy Q4; margin slipping","price_change_history":"+$0.25 60d ago, −5% volume","customer_segments":"Coffee aficionados; high sensitivity","optimization_signals":"Delay further increases"},

{"item_id":"7","item_name":"Mocha","item_basics":"7 | Mocha | Hot Drinks | $5.25 | $1.55 | 70.5%","sales_metrics":"Momentum 0.04; 827/58d; peak May; 1.0/order","elasticity_indicators":"E 4.69 (high)","competitive_position":"Comp $4.75; Δ +10.5%; premium","cost_dynamics":"Chocolate cost volatile (+4%); margin stable","price_change_history":"+$0.25 120d ago, −7% volume","customer_segments":"Treat buyers; high sensitivity","optimization_signals":"Test bundling vs price cut"},

{"item_id":"8","item_name":"Hot Chocolate","item_basics":"8 | Hot Chocolate | Hot Drinks | $4.25 | $1.15 | 72.9%","sales_metrics":"Momentum 0.01; 865/59d; strong Dec seasonality (+50%)","elasticity_indicators":"E 2.31 (high)","competitive_position":"Comp $3.50; Δ +21.4%; premium","cost_dynamics":"Cocoa up 5% Q4; margin still 70%+","price_change_history":"None","customer_segments":"Families/kids; high sensitivity","optimization_signals":"Consider winter promo price"},

{"item_id":"9","item_name":"Chai Latte","item_basics":"9 | Chai Latte | Hot Drinks | $4.95 | $1.45 | 70.7%","sales_metrics":"Momentum 0.01; 827/59d; weak seasonality","elasticity_indicators":"E 6.27 (very high)","competitive_position":"Comp $4.25; Δ +16.5%; premium","cost_dynamics":"Spice cost steady","price_change_history":"+$0.25 90d ago, −8% volume","customer_segments":"Health-oriented; very price sensitive","optimization_signals":"Price cut/test size downsizing"},

{"item_id":"10","item_name":"Drip Coffee","item_basics":"10 | Drip Coffee | Hot Drinks | $2.95 | $0.55 | 81.4%","sales_metrics":"Momentum 0.02; 785/59d; peak May; 1.2/order","elasticity_indicators":"E 1.73 (high)","competitive_position":"Comp $2.75; Δ +7.3%; premium","cost_dynamics":"Beans stable; margin best-in-class","price_change_history":"+$0.10 60d ago, −2% volume","customer_segments":"Bulk coffee drinkers; high sensitivity","optimization_signals":"Maintain—margin high, volume steady"},

{"item_id":"11","item_name":"Macchiato","item_basics":"11 | Macchiato | Hot Drinks | $3.75 | $0.95 | 74.7%","sales_metrics":"Momentum 0.04; 853/58d; peak May","elasticity_indicators":"E 0.98 (med)","competitive_position":"Comp $3.00; Δ +25.0%; premium","cost_dynamics":"Cost flat; margin solid","price_change_history":"No changes","customer_segments":"Coffee purists; med sensitivity","optimization_signals":"Monitor competitor rise; may need small cut"},

{"item_id":"12","item_name":"Iced Coffee","item_basics":"12 | Iced Coffee | Cold Drinks | $3.75 | $0.85 | 77.3%","sales_metrics":"Momentum 0.06; 793/59d; peak Jul (+55%)","elasticity_indicators":"E 1.46 (med-elastic)","competitive_position":"Comp $4.25; Δ −11.8%; value","cost_dynamics":"Ice/coffee cost steady","price_change_history":"None","customer_segments":"Students/summer crowd; med sensitivity","optimization_signals":"Potential +5% before summer peak"},

{"item_id":"13","item_name":"Iced Latte","item_basics":"13 | Iced Latte | Cold Drinks | $5.25 | $1.45 | 72.4%","sales_metrics":"Momentum 0.13; 792/58d; peak May","elasticity_indicators":"E 3.28 (high)","competitive_position":"No comps; premium","cost_dynamics":"Cost flat","price_change_history":"None","customer_segments":"Young professionals; high sensitivity","optimization_signals":"Bundle with bakery; avoid price hike"},

{"item_id":"14","item_name":"Cold Brew","item_basics":"14 | Cold Brew | Cold Drinks | $4.95 | $1.10 | 77.8%","sales_metrics":"Momentum −0.02; 869/59d; peak Jul (+52%)","elasticity_indicators":"E 2.61 (high)","competitive_position":"Comp $4.35; Δ +13.8%; premium","cost_dynamics":"Coffee cost stable","price_change_history":"None","customer_segments":"Trend seekers; high sensitivity","optimization_signals":"Consider small $-0.25 cut to boost share"},

{"item_id":"15","item_name":"Nitro Cold Brew","item_basics":"15 | Nitro Cold Brew | Cold Drinks | $5.75 | $1.35 | 76.5%","sales_metrics":"Momentum −0.04; 828/58d; peak Jul","elasticity_indicators":"E 6.58 (very high)","competitive_position":"No comps; premium","cost_dynamics":"Nitro gas cost flat","price_change_history":"None","customer_segments":"Enthusiasts; very price sensitive","optimization_signals":"Test off-peak discounts"},

{"item_id":"16","item_name":"Iced Americano","item_basics":"16 | Iced Americano | Cold Drinks | $3.95 | $0.85 | 78.5%","sales_metrics":"Momentum 0.02; 801/59d; peak May","elasticity_indicators":"E 4.81 (high)","competitive_position":"No comps; premium","cost_dynamics":"Cost stable","price_change_history":"None","customer_segments":"Calorie-aware; high sensitivity","optimization_signals":"Maintain price; watch elasticity"},

{"item_id":"17","item_name":"Iced Mocha","item_basics":"17 | Iced Mocha | Cold Drinks | $5.75 | $1.65 | 71.3%","sales_metrics":"Momentum 0.10; 847/59d; peak May","elasticity_indicators":"E 1.53 (high)","competitive_position":"No comps","cost_dynamics":"Chocolate volatile","price_change_history":"None","customer_segments":"Treat buyers; high sensitivity","optimization_signals":"Introduce loyalty reward instead of price cut"},

{"item_id":"18","item_name":"Frappuccino","item_basics":"18 | Frappuccino | Cold Drinks | $5.95 | $1.85 | 69.0%","sales_metrics":"Momentum 0.06; 915/59d; peak Jul (+55%)","elasticity_indicators":"E 3.60 (high)","competitive_position":"No comps","cost_dynamics":"Ice cream cost rising 3%","price_change_history":"None","customer_segments":"Teen & afternoon crowd; high sensitivity","optimization_signals":"Seasonal promo bundles"},

{"item_id":"19","item_name":"Vanilla Frappuccino","item_basics":"19 | Vanilla Frapp | Cold Drinks | $6.25 | $2.00 | 68.0%","sales_metrics":"Momentum 0.00; 781/58d; peak May","elasticity_indicators":"E 0.89 (med)","competitive_position":"No comps","cost_dynamics":"Vanilla cost up 4%","price_change_history":"None","customer_segments":"Sweet-tooth; med sensitivity","optimization_signals":"Hold price; monitor cost"},

{"item_id":"20","item_name":"Caramel Frappuccino","item_basics":"20 | Caramel Frapp | Cold Drinks | $6.50 | $2.10 | 67.7%","sales_metrics":"Momentum 0.02; 809/58d","elasticity_indicators":"E 2.75 (high)","competitive_position":"No comps","cost_dynamics":"Caramel cost +3%","price_change_history":"None","customer_segments":"Treat buyers; high sensitivity","optimization_signals":"Bundle upsell w/ bakery item"},

{"item_id":"21","item_name":"Iced Tea","item_basics":"21 | Iced Tea | Cold Drinks | $3.50 | $0.60 | 82.9%","sales_metrics":"Momentum 0.01; 835/59d; peak May","elasticity_indicators":"E 3.68 (high)","competitive_position":"Comp $2.75; Δ +27.3%; premium","cost_dynamics":"Tea cost flat","price_change_history":"None","customer_segments":"Health-oriented; high sensitivity","optimization_signals":"Test $-0.25 price to gain share"},

{"item_id":"22","item_name":"Croissant","item_basics":"22 | Croissant | Bakery | $3.25 | $1.05 | 67.7%","sales_metrics":"Momentum 0.03; 720/59d; peak May breakfast","elasticity_indicators":"E 3.81 (high)","competitive_position":"No comps","cost_dynamics":"Butter cost volatile Q4","price_change_history":"None","customer_segments":"Breakfast seekers; high sensitivity","optimization_signals":"Introduce multi-buy discount"},

{"item_id":"23","item_name":"Blueberry Muffin","item_basics":"23 | Blueberry Muffin | Bakery | $3.50 | $1.15 | 67.1%","sales_metrics":"Momentum 0.06; 776/58d","elasticity_indicators":"E 4.67 (high)","competitive_position":"No comps","cost_dynamics":"Berry cost seasonal (+5% summer)","price_change_history":"None","customer_segments":"Snack buyers; high sensitivity","optimization_signals":"Seasonal price adjustment post-summer"},

{"item_id":"24","item_name":"Chocolate Chip Cookie","item_basics":"24 | Cookie | Bakery | $2.95 | $0.85 | 71.2%","sales_metrics":"Momentum 0.01; 751/58d","elasticity_indicators":"E 0.85 (med-inelastic)","competitive_position":"No comps","cost_dynamics":"Chocolate up 4%","price_change_history":"None","customer_segments":"Impulse add-on; low sensitivity","optimization_signals":"Possible +5% without demand loss"},

{"item_id":"25","item_name":"Bagel","item_basics":"25 | Bagel | Bakery | $2.75 | $0.75 | 72.7%","sales_metrics":"Momentum 0.01; 762/58d; peak weekends","elasticity_indicators":"E 1.42 (med)","competitive_position":"Comp $2.50; Δ +10.0%; premium","cost_dynamics":"Flour cost rising 2%","price_change_history":"None","customer_segments":"Breakfast; med sensitivity","optimization_signals":"Hold—competitor price low"},

{"item_id":"26","item_name":"Bagel w/ Cream Cheese","item_basics":"26 | Bagel + CC | Bakery | $3.95 | $1.25 | 68.4%","sales_metrics":"Momentum 0.02; 789/59d","elasticity_indicators":"E 1.80 (high)","competitive_position":"No comps","cost_dynamics":"Cream cheese cost up 3%","price_change_history":"None","customer_segments":"Breakfast; high sensitivity","optimization_signals":"Offer combo savings vs solo items"},

{"item_id":"27","item_name":"Breakfast Sandwich","item_basics":"27 | Breakfast Sand. | Bakery | $5.95 | $2.35 | 60.5%","sales_metrics":"Momentum 0.06; 804/58d","elasticity_indicators":"E 1.15 (med)","competitive_position":"No comps","cost_dynamics":"Egg cost volatile; margin thin","price_change_history":"None","customer_segments":"Morning commuters; med sensitivity","optimization_signals":"Review recipe cost or +$0.25"},

{"item_id":"28","item_name":"Cinnamon Roll","item_basics":"28 | Cinnamon Roll | Bakery | $4.25 | $1.45 | 65.9%","sales_metrics":"Momentum 0.14; 786/58d","elasticity_indicators":"E 1.28 (med)","competitive_position":"No comps","cost_dynamics":"Sugar up 3%","price_change_history":"None","customer_segments":"Treat buyers; med sensitivity","optimization_signals":"Limited-time frosting add-on upsell"},

{"item_id":"29","item_name":"Banana Bread","item_basics":"29 | Banana Bread | Bakery | $3.75 | $1.20 | 68.0%","sales_metrics":"Momentum 0.05; 742/59d","elasticity_indicators":"E 1.50 (high)","competitive_position":"No comps","cost_dynamics":"Banana cost stable","price_change_history":"None","customer_segments":"Snack; high sensitivity","optimization_signals":"Bundle coffee +$0.25 upsell"},

{"item_id":"30","item_name":"Scone","item_basics":"30 | Scone | Bakery | $3.50 | $1.10 | 68.6%","sales_metrics":"Momentum 0.04; 796/58d","elasticity_indicators":"E 0.75 (med-inelastic)","competitive_position":"No comps","cost_dynamics":"Berry/add-ins seasonal","price_change_history":"None","customer_segments":"Afternoon tea; low sensitivity","optimization_signals":"Safe +5% test"},

{"item_id":"31","item_name":"Caramel Macchiato","item_basics":"31 | Caramel Macchiato | Specialty | $5.50 | $1.65 | 70.0%","sales_metrics":"Momentum 0.02; 848/59d","elasticity_indicators":"E 7.16 (very high)","competitive_position":"Comp $5.45; Δ +0.9%; parity","cost_dynamics":"Caramel cost +3%","price_change_history":"None","customer_segments":"Treat buyers; very sensitive","optimization_signals":"Avoid increases; consider rewards"},

{"item_id":"32","item_name":"Pumpkin Spice Latte","item_basics":"32 | PSL | Specialty | $5.95 | $1.85 | 68.9%","sales_metrics":"Momentum −0.02; 905/59d; strong Oct peak (+74%)","elasticity_indicators":"E 1.91 (high)","competitive_position":"No comps","cost_dynamics":"Spice cost seasonal","price_change_history":"None","customer_segments":"Seasonal trend; high sensitivity","optimization_signals":"Maintain price; leverage scarcity"},

{"item_id":"33","item_name":"Vanilla Latte","item_basics":"33 | Vanilla Latte | Specialty | $5.25 | $1.55 | 70.5%","sales_metrics":"Momentum −0.02; 814/58d","elasticity_indicators":"E 2.34 (high)","competitive_position":"No comps","cost_dynamics":"Vanilla cost rising","price_change_history":"None","customer_segments":"Flavor seekers; high sensitivity","optimization_signals":"Introduce sugar-free option premium"},

{"item_id":"34","item_name":"Hazelnut Latte","item_basics":"34 | Hazelnut Latte | Specialty | $5.25 | $1.55 | 70.5%","sales_metrics":"Momentum 0.01; 833/58d","elasticity_indicators":"E 2.43 (high)","competitive_position":"No comps","cost_dynamics":"Nut flavor cost stable","price_change_history":"None","customer_segments":"Flavor seekers; high sensitivity","optimization_signals":"Test limited-time topping upsell"},

{"item_id":"35","item_name":"White Chocolate Mocha","item_basics":"35 | White Choc Mocha | Specialty | $5.75 | $1.75 | 69.6%","sales_metrics":"Momentum 0.00; 871/59d","elasticity_indicators":"E 1.73 (high)","competitive_position":"Comp $5.45; Δ +5.5%; premium","cost_dynamics":"White choc cost volatile","price_change_history":"None","customer_segments":"Sweet-tooth; high sensitivity","optimization_signals":"Monitor competitor price drop"},

{"item_id":"36","item_name":"Matcha Latte","item_basics":"36 | Matcha Latte | Specialty | $5.50 | $1.75 | 68.2%","sales_metrics":"Momentum −0.12; 1,455/58d; peak Apr","elasticity_indicators":"E 2.88 (high)","competitive_position":"Comp $5.00; Δ +10.0%; premium","cost_dynamics":"Matcha powder +4%","price_change_history":"None","customer_segments":"Health/tea crowd; high sensitivity","optimization_signals":"Consider size-based pricing"},

{"item_id":"40","item_name":"Test Coffee","item_basics":"40 | Test Coffee | From Sq | $4.99 | N/A | N/A","sales_metrics":"Momentum 1.00 increasing; 76/13d; insufficient history","elasticity_indicators":"N/A","competitive_position":"No comps","cost_dynamics":"N/A","price_change_history":"No changes","customer_segments":"Trial users","optimization_signals":"Collect data before pricing"},

{"item_id":"41","item_name":"Test Croissant","item_basics":"41 | Test Croissant | From Sq | $2.99 | N/A | N/A","sales_metrics":"1 sale; insufficient data","elasticity_indicators":"N/A","competitive_position":"No comps","cost_dynamics":"N/A","price_change_history":"None","customer_segments":"Unknown","optimization_signals":"Await data"},

{"item_id":"42","item_name":"Demo Latte","item_basics":"42 | Demo Latte | From Sq | $4.50 | N/A | N/A","sales_metrics":"2 sales; insufficient data","elasticity_indicators":"N/A","competitive_position":"No comps","cost_dynamics":"N/A","price_change_history":"None","customer_segments":"Unknown","optimization_signals":"Await data"}
]
"""